### ISSUE TITLE
Netherite Axe Balancing

### ISSUE THREAD

**Issue by Ayutac** [Levoment/SuperAxes#5]
The Netherite Axe currently needs 3 Ingots and 2 Blocks, or 11 Ingots, or 44 Ancient Debris which is rarer than Diamond Ore. This takes about 22 Ancient Debris Veins, because they only spawn 1-3 Blocks (and I mostly encountered one). In comparison the 11 Diamonds can be mined with 2-3 Diamond Ore Veins, or 1 if having Fortune III and a bit of luck. This is an unreasonable increase of resources and effort for a dimishing return.

I propose to only use one Nether Ingot to upgrade a Diamond Axe to a Netherite one as it is done for all vanilla tools, and upgrading it with a Smithing Table instead of a Crafting Table just like the vanilla items. If you feel that this makes the Netherite Axe too cheap, maybe you can upgrade it with a Netherite Block instead on the Smithing Table, but I wouldn't recommend that pricing.

**Comment by Levoment** [comment]
Thanks for the feedback. I have changed the recipe to be an upgrade instead on the smithing table. One Diamond SuperAxe and a Netherite Ingot now yield a Netherite SuperAxe. The release with the update can be found on the releases page: [[1.16.1] SuperAxes 1.1.4](https://github.com/Levoment/SuperAxes/releases/tag/refs%2Fheads%2Frelease%2F1.1.4)

**Comment by Ayutac** [comment]
I can't calculate, it would have been 21 (2*9+3) ingots of course, which would have made it even worse. Thanks for change :)
