### ISSUE TITLE
Break a log with a banner using superaxe will receive white banner instead

### ISSUE THREAD

**Issue by linzexin022** [Levoment/SuperAxes#8]
Hi there, I broke logs with a Ominous Banner on it using Superaxe and received white banner instead.

**Comment by Levoment** [comment]
Hi,

Thanks for the issue.

I was able to recreate the problem and I can see the Ominous Banners get their data effectively removed when a log that has it attached is mined through the SuperAxe method unless the player is sneaking when breaking a single log containing an Ominous Banner.

I tried to see if I could drop the item manually instead, but I can't seem to be able to keep the banner data when dropping it.

For now I don't have a solution, but I'll leave the issue open for a while in case anyone has a solution and would like to make a pull request for it.

**Comment by Levoment** [comment]
The fix for this problem can be found on release: [2.0.11](https://github.com/Levoment/SuperAxes/releases/tag/refs%2Fheads%2Frelease%2F2.0.11)
Commit: [e2c63fba5b00b9086a3026b950d815343f9b7739](https://github.com/Levoment/SuperAxes/commit/e2c63fba5b00b9086a3026b950d815343f9b7739)
