### ISSUE TITLE
Crashes in 1.18.2

### ISSUE THREAD

**Issue by BeardedThorgi** [Levoment/SuperAxes#9]
The mod works great in 1.18.1, but while testing mods to update to 1.18.2, it crashes on attempting to open. See the below error and attached log for details.

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'superaxes'!
Exit Code: -
[crash-2022-03-19_00.17.08-client.txt](https://github.com/Levoment/SuperAxes/files/8308773/crash-2022-03-19_00.17.08-client.txt)
1

**Comment by Levoment** [comment]
Hi. Sorry I didn't see this issue. The problem has been fixed by bumping the version of the mod to 1.18.2. The release that can be used on 1.18.2 can be found on the releases page of this repository: 

https://github.com/Levoment/SuperAxes/releases/tag/refs%2Fheads%2Frelease%2F3.0.3
